var MITRE=[{id:"TA0001",n:"Initial Access",c:"#ef4444"},{id:"TA0002",n:"Execution",c:"#f97316"},{id:"TA0003",n:"Persistence",c:"#ec4899"},{id:"TA0004",n:"Priv Escalation",c:"#d946ef"},{id:"TA0005",n:"Defense Evasion",c:"#22c55e"},{id:"TA0006",n:"Credential Access",c:"#3b82f6"},{id:"TA0007",n:"Discovery",c:"#06b6d4"},{id:"TA0008",n:"Lateral Movement",c:"#eab308"},{id:"TA0009",n:"Collection",c:"#f59e0b"},{id:"TA0010",n:"Exfiltration",c:"#ef4444"},{id:"TA0011",n:"C2",c:"#a855f7"},{id:"TA0040",n:"Impact",c:"#dc2626"}];
// ATT&CK technique-level data — id: technique ID, tid: parent tactic, p: parent technique (sub-techniques only)
var MITRE_TECHNIQUES=[
  // TA0001 Initial Access
  {id:"T1566",  tid:"TA0001",n:"Phishing"},
  {id:"T1566.001",tid:"TA0001",n:"Spearphishing Attachment",p:"T1566"},
  {id:"T1566.002",tid:"TA0001",n:"Spearphishing Link",p:"T1566"},
  {id:"T1190",  tid:"TA0001",n:"Exploit Public-Facing App"},
  {id:"T1133",  tid:"TA0001",n:"External Remote Services"},
  {id:"T1078",  tid:"TA0001",n:"Valid Accounts"},
  {id:"T1199",  tid:"TA0001",n:"Trusted Relationship"},
  {id:"T1195",  tid:"TA0001",n:"Supply Chain Compromise"},
  // TA0002 Execution
  {id:"T1059",  tid:"TA0002",n:"Command and Scripting Interpreter"},
  {id:"T1059.001",tid:"TA0002",n:"PowerShell",p:"T1059"},
  {id:"T1059.003",tid:"TA0002",n:"Windows Command Shell",p:"T1059"},
  {id:"T1059.005",tid:"TA0002",n:"Visual Basic",p:"T1059"},
  {id:"T1059.007",tid:"TA0002",n:"JavaScript",p:"T1059"},
  {id:"T1204",  tid:"TA0002",n:"User Execution"},
  {id:"T1204.001",tid:"TA0002",n:"Malicious Link",p:"T1204"},
  {id:"T1204.002",tid:"TA0002",n:"Malicious File",p:"T1204"},
  {id:"T1053",  tid:"TA0002",n:"Scheduled Task/Job"},
  {id:"T1053.005",tid:"TA0002",n:"Scheduled Task",p:"T1053"},
  {id:"T1047",  tid:"TA0002",n:"Windows Management Instrumentation"},
  {id:"T1569",  tid:"TA0002",n:"System Services"},
  {id:"T1569.002",tid:"TA0002",n:"Service Execution",p:"T1569"},
  {id:"T1106",  tid:"TA0002",n:"Native API"},
  // TA0003 Persistence
  {id:"T1547",  tid:"TA0003",n:"Boot or Logon Autostart Execution"},
  {id:"T1547.001",tid:"TA0003",n:"Registry Run Keys / Startup Folder",p:"T1547"},
  {id:"T1543",  tid:"TA0003",n:"Create or Modify System Process"},
  {id:"T1543.003",tid:"TA0003",n:"Windows Service",p:"T1543"},
  {id:"T1098",  tid:"TA0003",n:"Account Manipulation"},
  {id:"T1136",  tid:"TA0003",n:"Create Account"},
  {id:"T1136.001",tid:"TA0003",n:"Local Account",p:"T1136"},
  {id:"T1136.002",tid:"TA0003",n:"Domain Account",p:"T1136"},
  {id:"T1505",  tid:"TA0003",n:"Server Software Component"},
  {id:"T1505.003",tid:"TA0003",n:"Web Shell",p:"T1505"},
  {id:"T1546",  tid:"TA0003",n:"Event Triggered Execution"},
  // TA0004 Privilege Escalation
  {id:"T1548",  tid:"TA0004",n:"Abuse Elevation Control Mechanism"},
  {id:"T1548.002",tid:"TA0004",n:"Bypass UAC",p:"T1548"},
  {id:"T1134",  tid:"TA0004",n:"Access Token Manipulation"},
  {id:"T1134.001",tid:"TA0004",n:"Token Impersonation/Theft",p:"T1134"},
  {id:"T1068",  tid:"TA0004",n:"Exploitation for Privilege Escalation"},
  {id:"T1055",  tid:"TA0004",n:"Process Injection"},
  {id:"T1055.001",tid:"TA0004",n:"DLL Injection",p:"T1055"},
  {id:"T1055.012",tid:"TA0004",n:"Process Hollowing",p:"T1055"},
  // TA0005 Defense Evasion
  {id:"T1562",  tid:"TA0005",n:"Impair Defenses"},
  {id:"T1562.001",tid:"TA0005",n:"Disable or Modify Tools",p:"T1562"},
  {id:"T1562.004",tid:"TA0005",n:"Disable or Modify System Firewall",p:"T1562"},
  {id:"T1112",  tid:"TA0005",n:"Modify Registry"},
  {id:"T1036",  tid:"TA0005",n:"Masquerading"},
  {id:"T1036.005",tid:"TA0005",n:"Match Legitimate Name or Location",p:"T1036"},
  {id:"T1070",  tid:"TA0005",n:"Indicator Removal"},
  {id:"T1070.001",tid:"TA0005",n:"Clear Windows Event Logs",p:"T1070"},
  {id:"T1027",  tid:"TA0005",n:"Obfuscated Files or Information"},
  {id:"T1218",  tid:"TA0005",n:"System Binary Proxy Execution"},
  {id:"T1218.011",tid:"TA0005",n:"Rundll32",p:"T1218"},
  {id:"T1218.010",tid:"TA0005",n:"Regsvr32",p:"T1218"},
  {id:"T1055",  tid:"TA0005",n:"Process Injection"},
  // TA0006 Credential Access
  {id:"T1003",  tid:"TA0006",n:"OS Credential Dumping"},
  {id:"T1003.001",tid:"TA0006",n:"LSASS Memory",p:"T1003"},
  {id:"T1003.002",tid:"TA0006",n:"Security Account Manager",p:"T1003"},
  {id:"T1003.003",tid:"TA0006",n:"NTDS",p:"T1003"},
  {id:"T1110",  tid:"TA0006",n:"Brute Force"},
  {id:"T1110.001",tid:"TA0006",n:"Password Guessing",p:"T1110"},
  {id:"T1110.003",tid:"TA0006",n:"Password Spraying",p:"T1110"},
  {id:"T1558",  tid:"TA0006",n:"Steal or Forge Kerberos Tickets"},
  {id:"T1558.003",tid:"TA0006",n:"Kerberoasting",p:"T1558"},
  {id:"T1558.004",tid:"TA0006",n:"AS-REP Roasting",p:"T1558"},
  {id:"T1552",  tid:"TA0006",n:"Unsecured Credentials"},
  {id:"T1528",  tid:"TA0006",n:"Steal Application Access Token"},
  {id:"T1056",  tid:"TA0006",n:"Input Capture"},
  // TA0007 Discovery
  {id:"T1082",  tid:"TA0007",n:"System Information Discovery"},
  {id:"T1083",  tid:"TA0007",n:"File and Directory Discovery"},
  {id:"T1087",  tid:"TA0007",n:"Account Discovery"},
  {id:"T1087.001",tid:"TA0007",n:"Local Account",p:"T1087"},
  {id:"T1087.002",tid:"TA0007",n:"Domain Account",p:"T1087"},
  {id:"T1069",  tid:"TA0007",n:"Permission Groups Discovery"},
  {id:"T1069.002",tid:"TA0007",n:"Domain Groups",p:"T1069"},
  {id:"T1046",  tid:"TA0007",n:"Network Service Discovery"},
  {id:"T1016",  tid:"TA0007",n:"System Network Configuration Discovery"},
  {id:"T1057",  tid:"TA0007",n:"Process Discovery"},
  {id:"T1018",  tid:"TA0007",n:"Remote System Discovery"},
  {id:"T1033",  tid:"TA0007",n:"System Owner/User Discovery"},
  // TA0008 Lateral Movement
  {id:"T1021",  tid:"TA0008",n:"Remote Services"},
  {id:"T1021.001",tid:"TA0008",n:"Remote Desktop Protocol",p:"T1021"},
  {id:"T1021.002",tid:"TA0008",n:"SMB/Windows Admin Shares",p:"T1021"},
  {id:"T1021.006",tid:"TA0008",n:"Windows Remote Management",p:"T1021"},
  {id:"T1550",  tid:"TA0008",n:"Use Alternate Authentication Material"},
  {id:"T1550.002",tid:"TA0008",n:"Pass the Hash",p:"T1550"},
  {id:"T1550.003",tid:"TA0008",n:"Pass the Ticket",p:"T1550"},
  {id:"T1534",  tid:"TA0008",n:"Internal Spearphishing"},
  // TA0009 Collection
  {id:"T1005",  tid:"TA0009",n:"Data from Local System"},
  {id:"T1560",  tid:"TA0009",n:"Archive Collected Data"},
  {id:"T1114",  tid:"TA0009",n:"Email Collection"},
  {id:"T1114.002",tid:"TA0009",n:"Remote Email Collection",p:"T1114"},
  {id:"T1056",  tid:"TA0009",n:"Input Capture"},
  {id:"T1213",  tid:"TA0009",n:"Data from Information Repositories"},
  // TA0010 Exfiltration
  {id:"T1048",  tid:"TA0010",n:"Exfiltration Over Alternative Protocol"},
  {id:"T1567",  tid:"TA0010",n:"Exfiltration Over Web Service"},
  {id:"T1567.002",tid:"TA0010",n:"Exfiltration to Cloud Storage",p:"T1567"},
  {id:"T1041",  tid:"TA0010",n:"Exfiltration Over C2 Channel"},
  {id:"T1030",  tid:"TA0010",n:"Data Transfer Size Limits"},
  // TA0011 C2
  {id:"T1071",  tid:"TA0011",n:"Application Layer Protocol"},
  {id:"T1071.001",tid:"TA0011",n:"Web Protocols",p:"T1071"},
  {id:"T1071.004",tid:"TA0011",n:"DNS",p:"T1071"},
  {id:"T1095",  tid:"TA0011",n:"Non-Application Layer Protocol"},
  {id:"T1573",  tid:"TA0011",n:"Encrypted Channel"},
  {id:"T1572",  tid:"TA0011",n:"Protocol Tunneling"},
  {id:"T1090",  tid:"TA0011",n:"Proxy"},
  {id:"T1008",  tid:"TA0011",n:"Fallback Channels"},
  {id:"T1132",  tid:"TA0011",n:"Data Encoding"},
  // TA0040 Impact
  {id:"T1486",  tid:"TA0040",n:"Data Encrypted for Impact"},
  {id:"T1490",  tid:"TA0040",n:"Inhibit System Recovery"},
  {id:"T1489",  tid:"TA0040",n:"Service Stop"},
  {id:"T1485",  tid:"TA0040",n:"Data Destruction"},
  {id:"T1499",  tid:"TA0040",n:"Endpoint Denial of Service"},
  {id:"T1529",  tid:"TA0040",n:"System Shutdown/Reboot"},
  {id:"T1491",  tid:"TA0040",n:"Defacement"}
];
var PICERL=[
  {id:"P",n:"Preparation",nFr:"Préparation",c:"#3b82f6",
   d:"Set up tools, procedures and training\nbefore an incident occurs.",
   dFr:"Mettre en place outils, procédures et formations\navant qu'un incident ne survienne."},
  {id:"I",n:"Identification",nFr:"Identification",c:"#ef4444",
   d:"Detect and analyze the event to confirm\nif it is actually an incident.",
   dFr:"Détecter et analyser l'événement pour confirmer\ns'il s'agit réellement d'un incident."},
  {id:"C",n:"Containment",nFr:"Confinement",c:"#eab308",
   d:"Limit the spread of the incident\nand isolate compromised systems.",
   dFr:"Limiter la propagation de l'incident\net isoler les systèmes compromis."},
  {id:"E",n:"Eradication",nFr:"Éradication",c:"#dc2626",
   d:"Remove root causes, malware\nand all attack vectors.",
   dFr:"Supprimer la cause racine, les malwares\net tous les vecteurs d'attaque."},
  {id:"R",n:"Recovery",nFr:"Récupération",c:"#22c55e",
   d:"Restore and validate affected systems\nto resume normal operations.",
   dFr:"Restaurer et valider les systèmes affectés\npour reprendre les opérations normales."},
  {id:"L",n:"Lessons Learned",nFr:"Retour d'expérience",c:"#a855f7",
   d:"Document and analyze the incident\nto improve future response.",
   dFr:"Documenter et analyser l'incident\npour améliorer la réponse future."}
];
var VAR_CATS={
  host:  {lbl:"Hôte & Processus", c:"#0ea5e9"},
  id:    {lbl:"Identité",          c:"#a855f7"},
  net:   {lbl:"Réseau",            c:"#f97316"},
  file:  {lbl:"Fichier & Hash",    c:"#eab308"},
  time:  {lbl:"Temporel",          c:"#22c55e"},
  filter:{lbl:"Filtres",           c:"#6b7280"}
};
var VARS=[
  {id:"v1", key:"{{DeviceName}}",   lbl:"Nom du poste",      ph:"SRV-DC01",         tp:"t", cat:"host"},
  {id:"v6", key:"{{ProcessName}}", lbl:"Nom du processus",  ph:"pwsh.exe",         tp:"t", cat:"host"},
  {id:"v15",key:"{{RegistryKey}}", lbl:"Clé de registre",   ph:"HKLM\\Software\\", tp:"t", cat:"host"},
  {id:"v16",key:"{{ServiceName}}", lbl:"Service Windows",   ph:"WebClient",        tp:"t", cat:"host"},
  {id:"v2", key:"{{UserEmail}}",   lbl:"Email utilisateur", ph:"user@corp.com",    tp:"t", cat:"id"},
  {id:"v5", key:"{{Username}}",    lbl:"Nom SAM",           ph:"j.doe",            tp:"t", cat:"id"},
  {id:"v7", key:"{{Domain}}",      lbl:"Domaine AD",        ph:"contoso.com",      tp:"t", cat:"id"},
  {id:"v11",key:"{{AccountName}}",lbl:"Compte Windows",    ph:"DOMAIN\\user",     tp:"t", cat:"id"},
  {id:"v3", key:"{{IPAddress}}",   lbl:"Adresse IP source", ph:"10.0.0.50",        tp:"t", cat:"net"},
  {id:"v12",key:"{{RemoteIP}}",   lbl:"IP distante",       ph:"203.0.113.5",      tp:"t", cat:"net"},
  {id:"v8", key:"{{Port}}",        lbl:"Port",              ph:"443",              tp:"n", cat:"net"},
  {id:"v14",key:"{{URL}}",         lbl:"URL",               ph:"https://evil.com", tp:"t", cat:"net"},
  {id:"v9", key:"{{FileHash}}",    lbl:"Hash SHA256",       ph:"abc123...",        tp:"t", cat:"file"},
  {id:"v13",key:"{{FileName}}",   lbl:"Nom de fichier",    ph:"malware.exe",      tp:"t", cat:"file"},
  {id:"v4", key:"{{TimeRange}}",   lbl:"Plage de temps",    ph:"24h",              tp:"s", opts:["1h","4h","12h","24h","48h","7d","14d","30d"], cat:"time"},
  {id:"v10",key:"{{Threshold}}",  lbl:"Seuil",             ph:"10",               tp:"n", cat:"filter"}
];
var SEVKEYS=["critical","high","medium","low","info"];
var ENVS=["Defender","Sentinel","Both"];

// ═══════════════════════════════════════
// I18N — LANG + T() + timeAgo()
// ═══════════════════════════════════════
var LANG = {
  en:{
    // Navigation
    new_query:'New query',import:'Import',export:'Export',variables:'Variables',
    investigations:'Investigations',admin:'Admin',signout:'Sign out',repos:'Repos',watch:'Watch',
    // Auth
    login_label:'Login',passphrase:'Passphrase',signin_btn:'Sign in',
    no_account:'No account yet?',create_account:'Create account',
    demo_btn:'Demo access (read-only)',switch_lang_tip:'Passer en français',
    switch_theme_dark:'Dark mode',switch_theme_light:'Light mode',
    // Registration
    reg_title:'Create account',reg_subtitle:'Choose a login and passphrase.',
    reg_login_hint:'Letters, numbers, _ . - only.',
    reg_confirm_pw:'Confirm passphrase',reg_create_btn:'Create account',
    // Change password
    cpw_forced_title:'Password change required',cpw_title:'Change my passphrase',
    cpw_forced_desc:'You must set a new passphrase before continuing.',
    cpw_current:'Current passphrase',cpw_new:'New passphrase',
    cpw_confirm_lbl:'Confirm',cpw_save:'Save',cpw_min8:'minimum 8 characters',
    // Profile
    prof_title:'My account',prof_avatar:'Profile picture',prof_choose:'Choose',
    prof_no_image:'No image',prof_image_saved:'Image saved',prof_role:'Role',
    prof_team:'Team',prof_leave_team:'Leave team',prof_change_pw:'Change my passphrase',
    prof_save:'Save changes',
    // Generic
    close:'Close',cancel:'Cancel',save:'Save',save_changes:'Save changes',
    close_nosave:'Close without saving',
    are_you_sure:'Are you sure? This cannot be undone.',
    error:'Error',just_now:'Just now',ago:'ago',minutes_unit:'minutes',hours_unit:'hours',
    days_unit:'days',yesterday:'Yesterday',never:'Never',optional:'optional',
    total:'total',collections:'Collections',name_lbl:'Name',enabled_lbl:'Enabled',
    starred_on:'\u2605 Starred',starred_off:'\u2606',
    // Stats & Filters
    queries_label:'Queries',mitre_label:'MITRE ATT\u0026CK',platforms_label:'Platforms',
    severity_label:'Severity',sans_label:'SANS IR Cycle',platform_label:'Platform',
    clear_filters:'\u2715 Clear filters',search:'Search title, KQL, tags, MITRE, comments\u2026',
    all_queries:'All queries',no_queries:'No queries found',create:'+ Create',
    personal_folders:'Personal',new_folder:'+ New folder',side_collections:'Collections',
    // Detail panel
    det_move_to:'Move to folder\u2026',det_no_folder:'No folder',
    det_vars_title:'Query variables',det_var_not_filled:'{n} variable(s) not filled',
    det_copy_lang:'Copy {lang}',det_copy_resolved:'Copy resolved {lang}',
    det_comments_title:'REFERENCES \u0026 COMMENTS',det_no_comments:'No references yet.',
    det_loading_comments:'Loading...',
    det_cmt_placeholder:'Note, context, campaign link, MITRE ATT\u0026CK article\u2026',
    det_cmt_url:'Reference URL (optional)',det_cmt_add:'Add',
    det_last_synced:'Last synced',det_no_detail:'No detail available.',
    det_compatible_assumed:'No known tables detected \u2014 assumed compatible.',
    det_resolved_ready:'READY',det_export_btn:'Export',det_edit_btn:'\u270e Edit',
    det_delete_btn:'Delete',det_query_lbl:'{lang} QUERY',det_resolved_lbl:'{lang} RESOLVED',
    // Create modal
    cr_language:'Language',cr_title_lbl:'Title',cr_description:'Description',
    cr_new_title:'New query',cr_edit_title:'Edit query',cr_env:'Environment',
    cr_severity:'Severity',cr_folder:'Folder',cr_none_folder:'None',
    cr_playbook:'Playbook',cr_mitre:'MITRE',cr_sans:'SANS IR Cycle',
    cr_tags:'Tags',cr_tags_ph:'Add+Enter',cr_detected:'Detected: ',
    cr_save_query:'Save query',cr_save_changes:'Save changes',
    // Import
    imp_upload_desc:'Upload a JSON file exported from KQLab.',
    // Folder
    fld_new_title:'New folder',fld_name:'Name',fld_icon:'Icon (2 letters)',fld_create:'Create',
    // Var panel
    vp_title:'My Variables',
    vp_desc:'Pre-filled automatically in all your queries. Saved locally in your browser.',
    vp_filled_count:'{n} / {total} variables filled',vp_clear_all:'Clear all',
    vp_footer_hint:'Values filled here will be pre-filled in all your queries when opened.',
    vp_save_btn:'Save',
    // Watch
    cyber_alerts:'Cyber alerts',unread_alerts:'unread alerts',critical_alerts:'critical',
    refresh_feeds:'Refresh feeds',last_fetched:'Last fetched',read_full:'Read full article',
    dismiss:'Dismiss',with_matches:'With matches only',extracted_keywords:'Extracted keywords',
    matching_queries:'Matching queries',watch_banner:'new cyber alerts match your queries',
    watch_sources:'Feed sources',feed_type:'Feed type',no_articles:'No articles found',
    all_sources:'All sources',loading:'Loading\u2026',wv_unread_btn:'Unread',
    wsrc_no_sources:'No sources configured.',wsrc_add_title:'+ Add source',
    wsrc_name_lbl:'Name',wsrc_add_save:'Add \u0026 save',wsrc_del:'Del',wsrc_url:'URL',
    wdet_products:'Products',wdet_no_matches:'No matching queries found for this article.',mark_read:'Mark as read',lbl_folder:'Folder',
    // Env
    env_profile:'Environment',compatible:'Compatible',incompatible:'Incompatible',
    partial:'Partial',partial_compat:'Partially compatible',
    missing_license:'Missing license',missing_connector:'Missing connector',
    wrong_platform:'Wrong platform',configure_env:'Configure environment',
    no_profile:'No profile configured',no_env_profile:'No environment configured',
    check_compatibility:'Compatibility',env_check:'Environment check',
    tables_detected:'Tables detected',save_and_check:'Save \u0026 Check',
    your_licenses:'Your licenses',your_connectors:'Your connectors',
    custom_tables:'Custom tables',select_platform:'Select your platform',
    defender_xdr:'Defender XDR',sentinel:'Microsoft Sentinel',
    env_check_result:'Environment configured',unknown_compat:'Unknown',
    env_new_profile:'+ New profile',env_activate:'Activate',env_active:'ACTIVE',
    env_name:'Name',env_platform:'Platform',
    env_mde_note:'MDE P1 \u2014 DeviceProcessEvents, DeviceNetworkEvents, DeviceFileEvents\u2026 (included by default)',
    env_sent_note:'SecurityAlert, SecurityIncident, ThreatIntelligenceIndicator\u2026 (included by default)',
    env_custom_desc:'Custom Log Analytics tables, comma-separated. Always considered compatible.',
    env_cancel:'Cancel',
    // Repos
    repo_sources:'GitHub Repository Sources',sync_now:'Sync now',syncing:'Syncing\u2026',
    never_synced:'Never synced',synced_ago:'Synced',sync_success:'Sync complete',
    sync_error:'Sync error',new_queries:'new',updated_queries:'updated',
    locally_modified:'Locally modified',reset_upstream:'Reset to upstream',
    imported_from:'Imported from',add_repo:'+ Add repository',
    github_owner:'GitHub owner',github_repo:'GitHub repo',
    path_filter:'Path filter',file_format:'File format',add_and_sync:'Add \u0026 Sync now',
    queries_imported:'queries imported',
    repo_no_repos:'No repositories configured.',repo_enabled_lbl:'Enabled',
    repo_purge_imported:'Purge imported',repo_sync_all:'Sync all',repo_errors:'errors',repo_reparse:'Re-parse',repo_reparse_tip:'Force re-fetch and re-parse all files from GitHub (clears SHA cache)',repo_reparse_confirm:'This will re-fetch and re-parse all imported files. Continue?',repo_reparse_done:'{n} queries updated',
    repo_name_lbl:'Name',repo_branch:'Branch',repo_target_folder:'Target folder',
    repo_none_folder:'None (no folder)',
    // Admin
    admin_panel:'Admin Panel',admin_dashboard:'Dashboard',admin_users:'Users',
    admin_teams:'Teams',admin_queries:'Queries',admin_folders:'Folders',
    admin_investigations:'Investigations',admin_audit:'Audit Log',admin_settings:'Settings',
    admin_repos:'Repo Sources',admin_watch:'Cyber Watch',admin_threats:'Threat Intel',
    admin_fingerprint:'Environments',back_to_vault:'Back to Vault',
    create_user:'Create user',reset_password:'Reset password',
    force_change_pw:'Force password change',kill_sessions:'Kill all sessions',
    unlock_account:'Unlock account',delete_user:'Delete user',create_team:'Create team',
    add_member:'Add member',remove_member:'Remove',bulk_actions:'Bulk actions',
    export_csv:'Export CSV',purge_sessions:'Purge expired sessions',
    purge_audit:'Purge old logs',vacuum_db:'Vacuum database',
    export_backup:'Export backup',system_info:'System information',
    security_settings:'Security',maintenance:'Maintenance',
    recent_activity:'Recent activity',active_sessions:'Active sessions',
    confirm_delete:'Are you sure?',password_generated:'Generated password (copy now)',
    no_data:'No data',all_teams:'All teams',orphaned:'No folder',
    select_all:'Select all',kill_session:'Kill session',
    // Generic actions
    delete:'Delete',disabled_lbl:'Disabled',purge:'Purge',
    // Auth errors
    login_pw_required:'Login and passphrase are required.',
    login_min2:'Login: minimum 2 characters.',
    login_invalid_chars:'Login: letters, numbers, _ . - only.',
    pw_min8_err:'Passphrase: minimum 8 characters.',
    pw_mismatch:'Passphrases do not match.',
    pw_current_required:'Current passphrase is required.',
    welcome_user:'Welcome, {name}!',pw_updated:'Passphrase updated!',
    // Profile toasts
    prof_updated:'Profile updated',
    img_format_err:'Unsupported format (JPEG, PNG, WebP, GIF)',
    img_size_err:'Image too large (max 150\u00a0KB)',
    leave_team_confirm:'Leave your team?',left_team:'Left team',
    // Folder
    del_folder_confirm:'Delete folder "{name}"?',
    del_folder_keep_queries:'{n} queries will be kept without a folder.',
    folder_deleted:'Folder deleted',
    // Query
    del_query_confirm:'Delete "{title}"? This action is irreversible.',
    query_deleted:'Query deleted',query_updated:'Query updated',query_created:'Query created',
    // Comments
    cmt_empty:'Comment cannot be empty.',
    del_cmt_confirm:'Delete this comment?',cmt_updated:'Comment updated',
    // Var panel
    vp_saved:'{n} variable(s) saved',vars_cleared:'Variables cleared',
    // Env
    del_env_confirm:'Delete this profile?',name_required:'Name required',
    profile_saved:'Profile saved \u2713',
    // Repos
    repo_fields_required:'Name, owner and repo are required.',
    repo_purge_all_confirm:'Delete ALL imported queries from all repo sources and reset sync state?\n\nThis cannot be undone. You will need to re-sync to restore the queries.',
    purge_result:'Purged {n} imported queries',
    repo_purge_src_confirm:'Purge all imported queries from "{name}"?\n\nQueries will be deleted and sync will be reset.',
    queries_deleted_from:'{n} queries deleted \u2014 {name}',
    repo_del_confirm:'Delete this repository source? Imported queries will remain in the vault.',
    reset_upstream_confirm:'Reset to upstream? Your local changes will be lost.',
    reset_upstream_done:'Reset to upstream \u2713',
    // Watch
    del_source_confirm:'Delete source "{name}"?',
    source_added:'Source added',source_deleted:'Source deleted',
    name_url_required:'Name and URL required.',
    watch_refresh_result:'{new} new articles, {matched} matches',
    source_saved:'Source updated',copied:'Copied!',
    // Watch slide-in
    ws_dismiss:'Dismiss',ws_read_article:'Read article \u2197',ws_close:'Close',
    ws_no_matches:'No matching queries',
    ws_no_matches_sub:'None of your KQL queries match the keywords or CVEs in this article. Add tags to your queries to improve detection.',
    // Watch sources
    wsrc_test_btn:'Test feed',wsrc_testing:'Testing\u2026',
    watch_all_popular_added:'All popular sources are already added.',
    watch_view_list:'List',watch_view_compact:'Compact',watch_view_mosaic:'Mosaic',
    // Watch toolbar
    wv_days_7:'7d',wv_days_14:'14d',wv_days_30:'30d',
    wv_matched_only:'Matched only',wv_filter_unread:'Unread only',
    // Errors
    error_enter_url:'Enter a URL first',
    error_http:'{status} \u2014 {text}',
    // Auth / Login page
    login_subtitle:'KQL query manager for SOC teams',
    // Admin strings
    admin_search_users:'Search users\u2026',
    admin_search_queries:'Search queries\u2026',
    admin_col_login:'Login',admin_col_display:'Display name',admin_col_role:'Role',
    admin_col_team:'Team',admin_col_status:'Status',admin_col_sessions:'Sessions',
    admin_col_created:'Created',admin_col_title:'Title',admin_col_severity:'Severity',
    admin_col_actions:'Actions',admin_col_ip:'IP',admin_col_date:'Date',admin_col_action:'Action',
    admin_col_user:'User',admin_col_iocs:'IOCs',admin_col_findings:'Findings',
    admin_status_active:'Active',admin_status_locked:'Locked ({remaining}m)',
    admin_status_change_pw:'Change pw',
    admin_view_detail:'View detail',
    admin_empty_teams:'No teams. Create one to get started.',
    admin_select_user:'Select user to add\u2026',
    admin_empty_repos:'No repo sources configured.',
    admin_empty_watch:'No watch sources configured.',
    admin_tab_wip:'Tab not yet implemented.',
    admin_bulk_delete:'Delete selected',admin_bulk_severity:'Change severity\u2026',
    admin_from_date:'From',admin_to_date:'To',
    admin_apply:'Apply',admin_clear:'Clear',
    admin_db_active:'Active',admin_db_not_set:'NOT SET',
    admin_backup_desc:'Download a copy of kqlab.db',
    admin_backup_btn:'Download',
    admin_watch_interval:'Fetch feeds every',admin_watch_minutes:'minutes',
    admin_user_login:'Login',admin_user_display:'Display name',admin_user_role:'Role',
    admin_user_team:'Team',admin_no_team:'\u2014 No team',
    admin_done:'Done',admin_unlocked:'Unlocked',
    admin_session_killed:'Session killed',
    admin_user_deleted:'User deleted',
    admin_user_created:'User "{login}" created',
    admin_team_created:'Team created',admin_team_deleted:'Team deleted',
    admin_member_added:'Member added',admin_member_removed:'Member removed',
    admin_query_deleted:'Query deleted',admin_folder_deleted:'Folder deleted',
    admin_db_vacuumed:'Database vacuumed \u2713',
    admin_delete_team:'Delete team',
    admin_team_name:'Team name',admin_ph_team_name:'SOC Blue Team\u2026',
    admin_ph_env_name:'My SOC Environment',
    admin_ph_repo_name:'My Community Repo',
    admin_ph_gh_owner:'Azure',admin_ph_gh_repo:'Azure-Sentinel',
    admin_ph_path_filter:'Hunting Queries/',
    // Var panel groups
    'vars.group.host':'Host & Process','vars.group.identity':'Identity',
    'vars.group.network':'Network','vars.group.file':'File & Hash',
    'vars.group.temporal':'Temporal','vars.group.filters':'Filters',
    // Variable labels
    'var.DeviceName':'Device name','var.ProcessName':'Process name',
    'var.RegistryKey':'Registry key','var.ServiceName':'Windows service',
    'var.UserEmail':'User email','var.Username':'SAM name',
    'var.Domain':'AD domain','var.AccountName':'Windows account',
    'var.IPAddress':'Source IP address','var.RemoteIP':'Remote IP',
    'var.Port':'Port','var.URL':'URL',
    'var.FileHash':'SHA256 hash','var.FileName':'File name',
    'var.TimeRange':'Time range','var.Threshold':'Threshold'
  },
  fr:{
    // Navigation
    new_query:'Nouvelle requ\u00eate',import:'Importer',export:'Exporter',
    variables:'Variables',investigations:'Investigations',admin:'Admin',
    signout:'D\u00e9connexion',repos:'Repos',watch:'Veille',
    // Auth
    login_label:'Identifiant',passphrase:'Phrase secr\u00e8te',signin_btn:'Se connecter',
    no_account:'Pas encore de compte\u00a0?',create_account:'Cr\u00e9er un compte',
    demo_btn:'Acc\u00e8s d\u00e9mo (lecture seule)',switch_lang_tip:'Switch to English',
    switch_theme_dark:'Mode sombre',switch_theme_light:'Mode clair',
    // Registration
    reg_title:'Cr\u00e9er un compte',reg_subtitle:'Choisissez un login et une passphrase.',
    reg_login_hint:'Lettres, chiffres, _ . - uniquement.',
    reg_confirm_pw:'Confirmer la passphrase',reg_create_btn:'Cr\u00e9er le compte',
    // Change password
    cpw_forced_title:'Changement de passphrase requis',cpw_title:'Changer ma passphrase',
    cpw_forced_desc:'Vous devez d\u00e9finir une nouvelle passphrase avant de continuer.',
    cpw_current:'Passphrase actuelle',cpw_new:'Nouvelle passphrase',
    cpw_confirm_lbl:'Confirmer',cpw_save:'Enregistrer',cpw_min8:'minimum 8 caract\u00e8res',
    // Profile
    prof_title:'Mon compte',prof_avatar:'Photo de profil',prof_choose:'Choisir',
    prof_no_image:'Aucune image',prof_image_saved:'Image enregistr\u00e9e',
    prof_role:'R\u00f4le',prof_team:'\u00c9quipe',prof_leave_team:'Quitter l\u2019\u00e9quipe',
    prof_change_pw:'Changer ma passphrase',prof_save:'Sauvegarder',
    // Generic
    close:'Fermer',cancel:'Annuler',save:'Enregistrer',
    save_changes:'Enregistrer les modifications',close_nosave:'Fermer sans sauvegarder',
    are_you_sure:'Confirmer\u00a0? Cette action est irr\u00e9versible.',
    error:'Erreur',just_now:'\u00c0 l\u2019instant',ago:'il y a',
    minutes_unit:'minutes',hours_unit:'heures',days_unit:'jours',
    yesterday:'Hier',never:'Jamais',optional:'optionnel',
    total:'total',collections:'Collections',name_lbl:'Nom',enabled_lbl:'Activ\u00e9',
    starred_on:'\u2605 Favoris',starred_off:'\u2606',
    // Stats & Filters
    queries_label:'Requ\u00eates',mitre_label:'MITRE ATT\u0026CK',
    platforms_label:'Plateformes',severity_label:'S\u00e9v\u00e9rit\u00e9',
    sans_label:'Cycle IR SANS',platform_label:'Plateforme',
    clear_filters:'\u2715 Effacer les filtres',
    search:'Titre, KQL, tags, MITRE, commentaires\u2026',
    all_queries:'Toutes les requ\u00eates',no_queries:'Aucune requ\u00eate trouv\u00e9e',
    create:'+ Cr\u00e9er',personal_folders:'Personnel',new_folder:'+ Nouveau dossier',
    side_collections:'Collections',
    // Detail panel
    det_move_to:'D\u00e9placer vers\u2026',det_no_folder:'Aucun dossier',
    det_vars_title:'Variables de la query',
    det_var_not_filled:'{n} variable(s) non remplie(s)',
    det_copy_lang:'Copier {lang}',det_copy_resolved:'Copier {lang} r\u00e9solu',
    det_comments_title:'R\u00c9F\u00c9RENCES \u0026 COMMENTAIRES',
    det_no_comments:'Aucune r\u00e9f\u00e9rence pour l\u2019instant.',
    det_loading_comments:'Chargement...',
    det_cmt_placeholder:'Note, contexte, lien de campagne, article MITRE ATT\u0026CK\u2026',
    det_cmt_url:'URL de r\u00e9f\u00e9rence (optionnel)',det_cmt_add:'Ajouter',
    det_last_synced:'Derni\u00e8re sync',det_no_detail:'Aucun d\u00e9tail disponible.',
    det_compatible_assumed:'Aucune table d\u00e9tect\u00e9e \u2014 suppos\u00e9e compatible.',
    det_resolved_ready:'PR\u00caT',det_export_btn:'Exporter',det_edit_btn:'\u270e Modifier',
    det_delete_btn:'Supprimer',det_query_lbl:'{lang} QUERY',det_resolved_lbl:'{lang} R\u00c9SOLU',
    // Create modal
    cr_language:'Langage',cr_title_lbl:'Titre',cr_description:'Description',
    cr_new_title:'Nouvelle requ\u00eate',cr_edit_title:'Modifier la requ\u00eate',
    cr_env:'Environnement',cr_severity:'S\u00e9v\u00e9rit\u00e9',
    cr_folder:'Dossier',cr_none_folder:'Aucun',cr_playbook:'Playbook',
    cr_mitre:'MITRE',cr_sans:'Cycle IR SANS',cr_tags:'Tags',
    cr_tags_ph:'Ajouter+Entr\u00e9e',cr_detected:'D\u00e9tect\u00e9es\u00a0: ',
    cr_save_query:'Enregistrer la requ\u00eate',
    cr_save_changes:'Enregistrer les modifications',
    // Import
    imp_upload_desc:'Chargez un fichier JSON export\u00e9 depuis KQLab.',
    // Folder
    fld_new_title:'Nouveau dossier',fld_name:'Nom',fld_icon:'Ic\u00f4ne (2 lettres)',
    fld_create:'Cr\u00e9er',
    // Var panel
    vp_title:'Mes Variables',
    vp_desc:'Valeurs pr\u00e9-remplies automatiquement dans toutes vos queries. Sauvegard\u00e9es localement dans votre navigateur.',
    vp_filled_count:'{n} / {total} variables remplies',vp_clear_all:'Tout effacer',
    vp_footer_hint:'Les valeurs remplies ici seront pr\u00e9-remplies dans toutes vos queries \u00e0 l\u2019ouverture.',
    vp_save_btn:'Sauvegarder',
    // Watch
    cyber_alerts:'Alertes cyber',unread_alerts:'alertes non lues',critical_alerts:'critiques',
    refresh_feeds:'Rafra\u00eechir les flux',last_fetched:'Dernier rafra\u00eechissement',
    read_full:"Lire l'article complet",dismiss:'Masquer',
    with_matches:'Avec correspondances uniquement',extracted_keywords:'Mots-cl\u00e9s extraits',
    matching_queries:'Queries correspondantes',
    watch_banner:'nouvelles alertes cyber correspondent \u00e0 vos queries',
    watch_sources:'Sources de flux',feed_type:'Type de flux',
    no_articles:'Aucun article trouv\u00e9',all_sources:'Toutes les sources',
    loading:'Chargement\u2026',wv_unread_btn:'Non lues',
    wsrc_no_sources:'Aucune source configur\u00e9e.',wsrc_add_title:'+ Ajouter une source',
    wsrc_name_lbl:'Nom',wsrc_add_save:'Ajouter et sauvegarder',wsrc_del:'Suppr',wsrc_url:'URL',
    wdet_products:'Produits',wdet_no_matches:'Aucune requ\u00eate correspondante pour cet article.',mark_read:'Marquer comme lu',lbl_folder:'Dossier',
    // Env
    env_profile:'Environnement',compatible:'Compatible',incompatible:'Incompatible',
    partial:'Partiel',partial_compat:'Partiellement compatible',
    missing_license:'Licence manquante',missing_connector:'Connecteur manquant',
    wrong_platform:'Mauvaise plateforme',configure_env:'Configurer l\u2019environnement',
    no_profile:'Aucun profil configur\u00e9',no_env_profile:'Aucun environnement configur\u00e9',
    check_compatibility:'Compatibilit\u00e9',env_check:'V\u00e9rification d\u2019environnement',
    tables_detected:'Tables d\u00e9tect\u00e9es',save_and_check:'Sauvegarder et v\u00e9rifier',
    your_licenses:'Vos licences',your_connectors:'Vos connecteurs',
    custom_tables:'Tables personnalis\u00e9es',select_platform:'Choisissez votre plateforme',
    defender_xdr:'Defender XDR',sentinel:'Microsoft Sentinel',
    env_check_result:'Environnement configur\u00e9',unknown_compat:'Inconnu',
    env_new_profile:'+ Nouveau profil',env_activate:'Activer',env_active:'ACTIF',
    env_name:'Nom',env_platform:'Plateforme',
    env_mde_note:'MDE P1 \u2014 DeviceProcessEvents, DeviceNetworkEvents, DeviceFileEvents\u2026 (inclus par d\u00e9faut)',
    env_sent_note:'SecurityAlert, SecurityIncident, ThreatIntelligenceIndicator\u2026 (inclus par d\u00e9faut)',
    env_custom_desc:'Tables Log Analytics personnalis\u00e9es, s\u00e9par\u00e9es par des virgules. Toujours consid\u00e9r\u00e9es compatibles.',
    env_cancel:'Annuler',
    // Repos
    repo_sources:'Sources GitHub',sync_now:'Synchroniser',syncing:'Sync\u2026',
    never_synced:'Jamais synchronis\u00e9',synced_ago:'Synchronis\u00e9',
    sync_success:'Sync termin\u00e9',sync_error:'Erreur sync',
    new_queries:'nouvelles',updated_queries:'mises \u00e0 jour',
    locally_modified:'Modifi\u00e9 localement',reset_upstream:'R\u00e9initialiser',
    imported_from:'Import\u00e9 depuis',add_repo:'+ Ajouter un d\u00e9p\u00f4t',
    github_owner:'Propri\u00e9taire GitHub',github_repo:'D\u00e9p\u00f4t GitHub',
    path_filter:'Filtre de chemin',file_format:'Format de fichier',
    add_and_sync:'Ajouter et synchroniser',queries_imported:'requ\u00eates import\u00e9es',
    repo_no_repos:'Aucun d\u00e9p\u00f4t configur\u00e9.',repo_enabled_lbl:'Activ\u00e9',
    repo_purge_imported:'Purger les import\u00e9es',repo_sync_all:'Tout synchroniser',repo_reparse:'Re-parser',repo_reparse_tip:'Force le re-t\u00e9l\u00e9chargement et la re-analyse de tous les fichiers depuis GitHub',repo_reparse_confirm:'Cela va re-t\u00e9l\u00e9charger et re-analyser tous les fichiers import\u00e9s. Continuer?',repo_reparse_done:'{n} requ\u00eates mises \u00e0 jour',
    repo_errors:'erreurs',repo_name_lbl:'Nom',repo_branch:'Branche',
    repo_target_folder:'Dossier cible',repo_none_folder:'Aucun (pas de dossier)',
    // Admin
    admin_panel:'Administration',admin_dashboard:'Tableau de bord',
    admin_users:'Utilisateurs',admin_teams:'\u00c9quipes',admin_queries:'Requ\u00eates',
    admin_folders:'Dossiers',admin_investigations:'Investigations',
    admin_audit:'Journal d\u2019audit',admin_settings:'Param\u00e8tres',
    admin_repos:'Sources GitHub',admin_watch:'Veille Cyber',admin_threats:'Menaces',
    admin_fingerprint:'Environnements',back_to_vault:'Retour au Vault',
    create_user:'Cr\u00e9er un utilisateur',reset_password:'R\u00e9initialiser le mot de passe',
    force_change_pw:'Forcer le changement',kill_sessions:'Terminer les sessions',
    unlock_account:'D\u00e9bloquer le compte',delete_user:'Supprimer l\u2019utilisateur',
    create_team:'Cr\u00e9er une \u00e9quipe',add_member:'Ajouter un membre',
    remove_member:'Retirer',bulk_actions:'Actions group\u00e9es',
    export_csv:'Exporter en CSV',purge_sessions:'Purger les sessions expir\u00e9es',
    purge_audit:'Purger les anciens logs',vacuum_db:'Optimiser la base',
    export_backup:'Exporter une sauvegarde',system_info:'Informations syst\u00e8me',
    security_settings:'S\u00e9curit\u00e9',maintenance:'Maintenance',
    recent_activity:'Activit\u00e9 r\u00e9cente',active_sessions:'Sessions actives',
    confirm_delete:'Confirmer la suppression\u00a0?',
    password_generated:'Mot de passe g\u00e9n\u00e9r\u00e9 (copier maintenant)',
    no_data:'Aucune donn\u00e9e',all_teams:'Toutes les \u00e9quipes',
    orphaned:'Sans dossier',select_all:'Tout s\u00e9lectionner',
    kill_session:'Terminer la session',
    // Generic actions
    delete:'Supprimer',disabled_lbl:'D\u00e9sactiv\u00e9',purge:'Purger',
    // Auth errors
    login_pw_required:'Identifiant et passphrase requis.',
    login_min2:'Identifiant\u00a0: minimum 2 caract\u00e8res.',
    login_invalid_chars:'Identifiant\u00a0: lettres, chiffres, _ . - uniquement.',
    pw_min8_err:'Passphrase\u00a0: minimum 8 caract\u00e8res.',
    pw_mismatch:'Les passphrases ne correspondent pas.',
    pw_current_required:'Passphrase actuelle requise.',
    welcome_user:'Bienvenue, {name}\u00a0!',pw_updated:'Passphrase mise \u00e0 jour\u00a0!',
    // Profile toasts
    prof_updated:'Profil mis \u00e0 jour',
    img_format_err:'Format non support\u00e9 (JPEG, PNG, WebP, GIF)',
    img_size_err:'Image trop grande (max 150\u00a0Ko)',
    leave_team_confirm:'Quitter votre \u00e9quipe\u00a0?',left_team:'\u00c9quipe quitt\u00e9e',
    // Folder
    del_folder_confirm:'Supprimer le dossier "{name}"\u00a0?',
    del_folder_keep_queries:'Les {n} queries seront conserv\u00e9es sans dossier.',
    folder_deleted:'Dossier supprim\u00e9',
    // Query
    del_query_confirm:'Supprimer "{title}"\u00a0? Cette action est irr\u00e9versible.',
    query_deleted:'Query supprim\u00e9e',query_updated:'Query mise \u00e0 jour',query_created:'Query cr\u00e9\u00e9e',
    // Comments
    cmt_empty:'Le commentaire ne peut pas \u00eatre vide.',
    del_cmt_confirm:'Supprimer ce commentaire\u00a0?',cmt_updated:'Commentaire mis \u00e0 jour',
    // Var panel
    vp_saved:'{n} variable(s) sauvegard\u00e9e(s)',vars_cleared:'Variables effac\u00e9es',
    // Env
    del_env_confirm:'Supprimer ce profil\u00a0?',name_required:'Nom requis',
    profile_saved:'Profil sauvegard\u00e9 \u2713',
    // Repos
    repo_fields_required:'Nom, propri\u00e9taire et d\u00e9p\u00f4t requis.',
    repo_purge_all_confirm:'Supprimer TOUTES les queries import\u00e9es de toutes les sources et r\u00e9initialiser l\u2019\u00e9tat de sync\u00a0?\n\nCette action est irr\u00e9versible. Vous devrez resynchroniser pour restaurer les queries.',
    purge_result:'{n} queries import\u00e9es purg\u00e9es',
    repo_purge_src_confirm:'Purger toutes les queries import\u00e9es de "{name}"\u00a0?\n\nLes queries seront supprim\u00e9es et le sync r\u00e9initialis\u00e9.',
    queries_deleted_from:'{n} queries supprim\u00e9es \u2014 {name}',
    repo_del_confirm:'Supprimer cette source\u00a0? Les queries import\u00e9es resteront dans le vault.',
    reset_upstream_confirm:'R\u00e9initialiser depuis l\u2019amont\u00a0? Vos modifications locales seront perdues.',
    reset_upstream_done:'R\u00e9initialis\u00e9 depuis l\u2019amont \u2713',
    // Watch
    del_source_confirm:'Supprimer la source "{name}"\u00a0?',
    source_added:'Source ajout\u00e9e',source_deleted:'Source supprim\u00e9e',
    name_url_required:'Nom et URL requis.',
    watch_refresh_result:'{new} nouveaux articles, {matched} correspondances',
    source_saved:'Source mise \u00e0 jour',copied:'Copi\u00e9\u00a0!',
    // Watch slide-in
    ws_dismiss:'Ignorer',ws_read_article:'Lire l\u2019article \u2197',ws_close:'Fermer',
    ws_no_matches:'Aucune query correspondante',
    ws_no_matches_sub:'Aucune de vos queries KQL ne correspond aux mots-cl\u00e9s ou CVEs de cet article. Ajoutez des tags \u00e0 vos queries pour am\u00e9liorer la d\u00e9tection.',
    // Watch sources
    wsrc_test_btn:'Tester le feed',wsrc_testing:'Test en cours\u2026',
    watch_all_popular_added:'Toutes les sources populaires sont d\u00e9j\u00e0 ajout\u00e9es.',
    watch_view_list:'Liste',watch_view_compact:'Compact',watch_view_mosaic:'Mosa\u00efque',
    // Watch toolbar
    wv_days_7:'7j',wv_days_14:'14j',wv_days_30:'30j',
    wv_matched_only:'Avec correspondances',wv_filter_unread:'Non lus',
    // Errors
    error_enter_url:'Entrez d\u2019abord une URL',
    error_http:'{status} \u2014 {text}',
    // Auth / Login page
    login_subtitle:'Gestionnaire de requ\u00eates KQL pour \u00e9quipes SOC',
    // Admin strings
    admin_search_users:'Rechercher des utilisateurs\u2026',
    admin_search_queries:'Rechercher des requ\u00eates\u2026',
    admin_col_login:'Identifiant',admin_col_display:'Nom affich\u00e9',admin_col_role:'R\u00f4le',
    admin_col_team:'\u00c9quipe',admin_col_status:'Statut',admin_col_sessions:'Sessions',
    admin_col_created:'Cr\u00e9\u00e9',admin_col_title:'Titre',admin_col_severity:'S\u00e9v\u00e9rit\u00e9',
    admin_col_actions:'Actions',admin_col_ip:'IP',admin_col_date:'Date',admin_col_action:'Action',
    admin_col_user:'Utilisateur',admin_col_iocs:'IOCs',admin_col_findings:'Findings',
    admin_status_active:'Actif',admin_status_locked:'Verrouill\u00e9 ({remaining}m)',
    admin_status_change_pw:'Changer mdp',
    admin_view_detail:'Voir le d\u00e9tail',
    admin_empty_teams:'Aucune \u00e9quipe. Cr\u00e9ez-en une pour commencer.',
    admin_select_user:'S\u00e9lectionner un utilisateur\u2026',
    admin_empty_repos:'Aucune source GitHub configur\u00e9e.',
    admin_empty_watch:'Aucune source de veille configur\u00e9e.',
    admin_tab_wip:'Onglet non encore impl\u00e9ment\u00e9.',
    admin_bulk_delete:'Supprimer la s\u00e9lection',admin_bulk_severity:'Changer la s\u00e9v\u00e9rit\u00e9\u2026',
    admin_from_date:'Du',admin_to_date:'Au',
    admin_apply:'Appliquer',admin_clear:'R\u00e9initialiser',
    admin_db_active:'Actif',admin_db_not_set:'NON D\u00c9FINIE',
    admin_backup_desc:'T\u00e9l\u00e9charger une copie de kqlab.db',
    admin_backup_btn:'T\u00e9l\u00e9charger',
    admin_watch_interval:'R\u00e9cup\u00e9rer les flux toutes les',admin_watch_minutes:'minutes',
    admin_user_login:'Identifiant',admin_user_display:'Nom affich\u00e9',admin_user_role:'R\u00f4le',
    admin_user_team:'\u00c9quipe',admin_no_team:'\u2014 Aucune \u00e9quipe',
    admin_done:'Termin\u00e9',admin_unlocked:'D\u00e9bloqu\u00e9',
    admin_session_killed:'Session termin\u00e9e',
    admin_user_deleted:'Utilisateur supprim\u00e9',
    admin_user_created:'Utilisateur \u00ab\u202f{login}\u202f\u00bb cr\u00e9\u00e9',
    admin_team_created:'\u00c9quipe cr\u00e9\u00e9e',admin_team_deleted:'\u00c9quipe supprim\u00e9e',
    admin_member_added:'Membre ajout\u00e9',admin_member_removed:'Membre retir\u00e9',
    admin_query_deleted:'Requ\u00eate supprim\u00e9e',admin_folder_deleted:'Dossier supprim\u00e9',
    admin_db_vacuumed:'Base optimis\u00e9e \u2713',
    admin_delete_team:'Supprimer l\u2019\u00e9quipe',
    admin_team_name:'Nom de l\u2019\u00e9quipe',admin_ph_team_name:'SOC Blue Team\u2026',
    admin_ph_env_name:'Mon environnement SOC',
    admin_ph_repo_name:'Mon repo communautaire',
    admin_ph_gh_owner:'Azure',admin_ph_gh_repo:'Azure-Sentinel',
    admin_ph_path_filter:'Hunting Queries/',
    // Var panel groups
    'vars.group.host':'H\u00f4te & Processus','vars.group.identity':'Identit\u00e9',
    'vars.group.network':'R\u00e9seau','vars.group.file':'Fichier & Hash',
    'vars.group.temporal':'Temporel','vars.group.filters':'Filtres',
    // Variable labels
    'var.DeviceName':'Nom du poste','var.ProcessName':'Nom du processus',
    'var.RegistryKey':'Cl\u00e9 de registre','var.ServiceName':'Service Windows',
    'var.UserEmail':'Email utilisateur','var.Username':'Nom SAM',
    'var.Domain':'Domaine AD','var.AccountName':'Compte Windows',
    'var.IPAddress':'Adresse IP source','var.RemoteIP':'IP distante',
    'var.Port':'Port','var.URL':'URL',
    'var.FileHash':'Hash SHA256','var.FileName':'Nom de fichier',
    'var.TimeRange':'Plage de temps','var.Threshold':'Seuil'
  }
};
function T(k,params){
  // Delegate to i18n.t() — DICTS in i18n.js is the single source of truth
  if(typeof i18n!=='undefined'&&typeof i18n.t==='function'){return i18n.t(k,params);}
  // Fallback to LANG (when i18n.js hasn't loaded yet)
  var l=(typeof S!=='undefined'?S.uiLang:null)||'en';
  var text=(LANG[l]&&LANG[l][k])||(LANG.en&&LANG.en[k]);
  if(text===undefined){console.warn('[i18n] Missing key: '+k);return k;}
  if(params){Object.keys(params).forEach(function(pk){text=text.replace(new RegExp('\\{'+pk+'\\}','g'),params[pk]);});}
  return text;
}
function timeAgo(dt){
  var l=typeof i18n!=='undefined'?i18n.getLang():(typeof S!=='undefined'?S.uiLang:'en');
  if(!dt)return T('never');
  var diff=Date.now()-new Date(dt).getTime();
  var min=Math.floor(diff/60000);var hr=Math.floor(diff/3600000);var d=Math.floor(diff/86400000);
  if(min<1)return T('just_now');
  if(min<60)return min+' '+T('minutes_unit')+' '+T('ago');
  if(hr<24)return hr+' '+T('hours_unit')+' '+T('ago');
  if(d===1)return T('yesterday');
  if(d<30)return d+' '+T('days_unit')+' '+T('ago');
  return new Date(dt).toLocaleDateString(l==='fr'?'fr-FR':'en-US');
}

var LANGUAGES=[
  {
    id:"KQL",name:"KQL",desc:"Sentinel · Defender",color:"#0ea5e9",
    logo:'<svg viewBox="0 0 20 20" width="14" height="14" fill="none"><path d="M10 2L3 5v5.5c0 4 3.2 7 7 7.5 3.8-.5 7-3.5 7-7.5V5z" fill="#0ea5e9"/><path d="M7 10.5l2 2 4-4.5" stroke="white" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>'
  },
  {
    id:"ELK",name:"DSL",desc:"Elastic / ELK",color:"#F04E98",
    logo:'<svg viewBox="0 0 20 20" width="14" height="14"><rect x="1" y="1" width="18" height="5.5" rx="1.5" fill="#F04E98"/><rect x="1" y="7.5" width="18" height="5.5" rx="1.5" fill="#00BFB3"/><rect x="1" y="14" width="8" height="6" rx="1.5" fill="#0055A5"/><rect x="11" y="14" width="8" height="6" rx="1.5" fill="#FEC514"/></svg>'
  },
  {
    id:"SPL",name:"SPL",desc:"Splunk",color:"#65A637",
    logo:'<svg viewBox="0 0 20 20" width="14" height="14" fill="none"><rect x="1" y="1" width="18" height="18" rx="3.5" fill="#0D0D0D"/><path d="M7.5 6l5 4-5 4" stroke="#65A637" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'
  }
];
